package basicauth

import (
	"bytes"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"encoding/binary"
	"encoding/csv"
	"encoding/json"
	"errors"
	"fmt"
	"hash"
	"io"
	"os"
	"strconv"
	"strings"
	"sync"

	"github.com/oarkflow/fh"
)

const (
	defaultRealm          = "Restricted"
	defaultMaxHeaderBytes = 4096

	hashPrefix = "pbkdf2-sha256"
)

var (
	ErrUserNotFound      = errors.New("basicauth: user not found")
	ErrInvalidCredential = errors.New("basicauth: invalid credential")
	ErrInvalidHash       = errors.New("basicauth: invalid password hash")
	ErrDisabledUser      = errors.New("basicauth: disabled user")
)

// User is the stored user record.
// PasswordHash should contain a PBKDF2 hash generated by HashPassword.
type User struct {
	Username     string            `json:"username"`
	PasswordHash string            `json:"password_hash"`
	Enabled      bool              `json:"enabled"`
	Roles        []string          `json:"roles,omitempty"`
	Metadata     map[string]string `json:"metadata,omitempty"`
}

// Principal is the authenticated user exposed to callbacks.
type Principal struct {
	Username string
	Roles    []string
	Metadata map[string]string
}

// Storage is the pluggable user backend.
//
// Implementations may use memory, CSV, JSON, database, Redis, etc.
// The middleware only requires GetUser.
type Storage interface {
	GetUser(username string) (User, bool, error)
}

// Reloader is optional for file-backed stores.
type Reloader interface {
	Reload() error
}

// PasswordHasher verifies and creates password hashes.
type PasswordHasher interface {
	Hash(password string) (string, error)
	Verify(password string, encodedHash string) bool
}

// UnauthorizedHandler allows custom unauthorized responses.
type UnauthorizedHandler func(ctx *fh.Ctx, realm string) error

// AuthenticatedHandler runs after successful authentication and before ctx.Next().
type AuthenticatedHandler func(ctx *fh.Ctx, principal Principal) error

// Config controls the middleware behavior.
type Config struct {
	Realm string

	Storage Storage
	Hasher  PasswordHasher

	// MaxHeaderBytes prevents very large Authorization headers from wasting CPU/memory.
	// Default: 4096.
	MaxHeaderBytes int

	// RequireTLS rejects Basic Auth unless the request appears to be HTTPS.
	// Recommended in production behind TLS.
	RequireTLS bool

	// TrustProxyHeaders allows X-Forwarded-Proto / X-Forwarded-Ssl checks.
	// Enable only if your app is behind a trusted reverse proxy.
	TrustProxyHeaders bool

	UnauthorizedHandler UnauthorizedHandler
	OnAuthenticated     AuthenticatedHandler

	// DummyHash is used when a username does not exist.
	// This reduces username enumeration through timing differences.
	DummyHash string
}

// New keeps your old API working.
func New(username, password string) fh.HandlerFunc {
	hasher := DefaultHasher()
	hash, err := hasher.Hash(password)
	if err != nil {
		panic(err)
	}

	store := NewMemoryStorage()
	store.Set(User{
		Username:     username,
		PasswordHash: hash,
		Enabled:      true,
	})

	return NewWithConfig(Config{
		Storage: store,
		Hasher:  hasher,
		Realm:   defaultRealm,
	})
}

// NewWithConfig creates the Basic Auth middleware.
func NewWithConfig(config Config) fh.HandlerFunc {
	cfg := normalizeConfig(config)

	return func(ctx *fh.Ctx) error {
		if cfg.RequireTLS && !isHTTPS(ctx, cfg.TrustProxyHeaders) {
			return cfg.UnauthorizedHandler(ctx, cfg.Realm)
		}

		auth := ctx.Get("Authorization")
		if auth == "" || len(auth) > cfg.MaxHeaderBytes {
			return cfg.UnauthorizedHandler(ctx, cfg.Realm)
		}

		username, password, ok := parseBasicAuth(auth)
		if !ok {
			return cfg.UnauthorizedHandler(ctx, cfg.Realm)
		}

		user, found, err := cfg.Storage.GetUser(username)
		if err != nil {
			return cfg.UnauthorizedHandler(ctx, cfg.Realm)
		}

		if !found {
			// Verify against dummy hash to reduce username enumeration timing leaks.
			cfg.Hasher.Verify(password, cfg.DummyHash)
			return cfg.UnauthorizedHandler(ctx, cfg.Realm)
		}

		if !user.Enabled {
			// Still verify once to reduce observable timing difference for disabled users.
			cfg.Hasher.Verify(password, user.PasswordHash)
			return cfg.UnauthorizedHandler(ctx, cfg.Realm)
		}

		if !cfg.Hasher.Verify(password, user.PasswordHash) {
			return cfg.UnauthorizedHandler(ctx, cfg.Realm)
		}

		if cfg.OnAuthenticated != nil {
			err := cfg.OnAuthenticated(ctx, Principal{
				Username: user.Username,
				Roles:    cloneStrings(user.Roles),
				Metadata: cloneMap(user.Metadata),
			})
			if err != nil {
				return err
			}
		}

		return ctx.Next()
	}
}

func normalizeConfig(cfg Config) Config {
	if cfg.Realm == "" {
		cfg.Realm = defaultRealm
	}
	if cfg.MaxHeaderBytes <= 0 {
		cfg.MaxHeaderBytes = defaultMaxHeaderBytes
	}
	if cfg.Hasher == nil {
		cfg.Hasher = DefaultHasher()
	}
	if cfg.Storage == nil {
		cfg.Storage = NewMemoryStorage()
	}
	if cfg.UnauthorizedHandler == nil {
		cfg.UnauthorizedHandler = DefaultUnauthorizedHandler
	}
	if cfg.DummyHash == "" {
		hash, err := cfg.Hasher.Hash("invalid-password")
		if err != nil {
			panic(err)
		}
		cfg.DummyHash = hash
	}
	return cfg
}

func DefaultUnauthorizedHandler(ctx *fh.Ctx, realm string) error {
	ctx.Set("WWW-Authenticate", `Basic realm="`+escapeRealm(realm)+`", charset="UTF-8"`)
	return ctx.Status(401).SendString("Unauthorized")
}

func escapeRealm(realm string) string {
	realm = strings.ReplaceAll(realm, `\`, `\\`)
	realm = strings.ReplaceAll(realm, `"`, `\"`)
	return realm
}

func parseBasicAuth(header string) (username string, password string, ok bool) {
	if len(header) < 7 {
		return "", "", false
	}

	// Scheme is case-insensitive.
	if !equalFoldASCII(header[:6], "Basic ") {
		return "", "", false
	}

	encoded := strings.TrimSpace(header[6:])
	if encoded == "" {
		return "", "", false
	}

	decodedLen := base64.StdEncoding.DecodedLen(len(encoded))
	buf := make([]byte, decodedLen)

	n, err := base64.StdEncoding.Decode(buf, []byte(encoded))
	if err != nil {
		return "", "", false
	}

	buf = buf[:n]

	colon := bytes.IndexByte(buf, ':')
	if colon <= 0 {
		return "", "", false
	}

	username = string(buf[:colon])
	password = string(buf[colon+1:])

	if username == "" {
		return "", "", false
	}

	return username, password, true
}

func equalFoldASCII(a, b string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := 0; i < len(a); i++ {
		aa := a[i]
		bb := b[i]

		if 'A' <= aa && aa <= 'Z' {
			aa += 'a' - 'A'
		}
		if 'A' <= bb && bb <= 'Z' {
			bb += 'a' - 'A'
		}
		if aa != bb {
			return false
		}
	}
	return true
}

func isHTTPS(ctx *fh.Ctx, trustProxy bool) bool {
	// This keeps compatibility with custom fasthttp-like contexts.
	// If your Ctx exposes TLS state directly, you can customize this logic.

	if trustProxy {
		if strings.EqualFold(ctx.Get("X-Forwarded-Proto"), "https") {
			return true
		}
		if strings.EqualFold(ctx.Get("X-Forwarded-Ssl"), "on") {
			return true
		}
	}

	return false
}

// -----------------------------------------------------------------------------
// Memory storage
// -----------------------------------------------------------------------------

type MemoryStorage struct {
	mu    sync.RWMutex
	users map[string]User
}

func NewMemoryStorage() *MemoryStorage {
	return &MemoryStorage{
		users: make(map[string]User),
	}
}

func NewMemoryStorageFromUsers(users []User) *MemoryStorage {
	s := NewMemoryStorage()
	for _, u := range users {
		s.Set(u)
	}
	return s
}

func NewMemoryStorageFromPlain(users map[string]string) (*MemoryStorage, error) {
	hasher := DefaultHasher()
	s := NewMemoryStorage()

	for username, password := range users {
		hash, err := hasher.Hash(password)
		if err != nil {
			return nil, err
		}
		s.Set(User{
			Username:     username,
			PasswordHash: hash,
			Enabled:      true,
		})
	}

	return s, nil
}

func (s *MemoryStorage) GetUser(username string) (User, bool, error) {
	s.mu.RLock()
	user, ok := s.users[username]
	s.mu.RUnlock()

	if !ok {
		return User{}, false, nil
	}

	return cloneUser(user), true, nil
}

func (s *MemoryStorage) Set(user User) {
	s.mu.Lock()
	if s.users == nil {
		s.users = make(map[string]User)
	}
	s.users[user.Username] = cloneUser(user)
	s.mu.Unlock()
}

func (s *MemoryStorage) Delete(username string) {
	s.mu.Lock()
	delete(s.users, username)
	s.mu.Unlock()
}

func (s *MemoryStorage) Users() []User {
	s.mu.RLock()
	out := make([]User, 0, len(s.users))
	for _, user := range s.users {
		out = append(out, cloneUser(user))
	}
	s.mu.RUnlock()
	return out
}

// -----------------------------------------------------------------------------
// CSV storage
// -----------------------------------------------------------------------------
//
// CSV format:
//
// username,password_hash,enabled,roles
// admin,pbkdf2-sha256$150000$...$...,true,admin|manager
//
// Header row is optional.

type CSVStorage struct {
	path string

	mu    sync.RWMutex
	users map[string]User
}

func NewCSVStorage(path string) (*CSVStorage, error) {
	s := &CSVStorage{
		path:  path,
		users: make(map[string]User),
	}
	if err := s.Reload(); err != nil {
		return nil, err
	}
	return s, nil
}

func (s *CSVStorage) GetUser(username string) (User, bool, error) {
	s.mu.RLock()
	user, ok := s.users[username]
	s.mu.RUnlock()

	if !ok {
		return User{}, false, nil
	}

	return cloneUser(user), true, nil
}

func (s *CSVStorage) Reload() error {
	users, err := LoadUsersCSV(s.path)
	if err != nil {
		return err
	}

	next := make(map[string]User, len(users))
	for _, user := range users {
		next[user.Username] = cloneUser(user)
	}

	s.mu.Lock()
	s.users = next
	s.mu.Unlock()

	return nil
}

func LoadUsersCSV(path string) ([]User, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	r := csv.NewReader(f)
	r.TrimLeadingSpace = true
	r.FieldsPerRecord = -1

	var users []User
	rowIndex := 0

	for {
		row, err := r.Read()
		if errors.Is(err, io.EOF) {
			break
		}
		if err != nil {
			return nil, err
		}

		rowIndex++

		if len(row) == 0 {
			continue
		}

		for i := range row {
			row[i] = strings.TrimSpace(row[i])
		}

		if rowIndex == 1 && isCSVHeader(row) {
			continue
		}

		if len(row) < 2 {
			return nil, fmt.Errorf("basicauth: invalid CSV row %d: expected at least username,password_hash", rowIndex)
		}

		username := row[0]
		passwordHash := row[1]

		if username == "" {
			return nil, fmt.Errorf("basicauth: empty username at CSV row %d", rowIndex)
		}
		if passwordHash == "" {
			return nil, fmt.Errorf("basicauth: empty password_hash at CSV row %d", rowIndex)
		}

		enabled := true
		if len(row) >= 3 && row[2] != "" {
			enabled, err = strconv.ParseBool(row[2])
			if err != nil {
				return nil, fmt.Errorf("basicauth: invalid enabled value at CSV row %d: %w", rowIndex, err)
			}
		}

		var roles []string
		if len(row) >= 4 && row[3] != "" {
			roles = splitList(row[3])
		}

		users = append(users, User{
			Username:     username,
			PasswordHash: passwordHash,
			Enabled:      enabled,
			Roles:        roles,
		})
	}

	return users, nil
}

func SaveUsersCSV(path string, users []User) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	w := csv.NewWriter(f)

	if err := w.Write([]string{"username", "password_hash", "enabled", "roles"}); err != nil {
		return err
	}

	for _, user := range users {
		row := []string{
			user.Username,
			user.PasswordHash,
			strconv.FormatBool(user.Enabled),
			strings.Join(user.Roles, "|"),
		}
		if err := w.Write(row); err != nil {
			return err
		}
	}

	w.Flush()
	return w.Error()
}

func isCSVHeader(row []string) bool {
	if len(row) < 2 {
		return false
	}
	return strings.EqualFold(row[0], "username") &&
		(strings.EqualFold(row[1], "password_hash") || strings.EqualFold(row[1], "password"))
}

// -----------------------------------------------------------------------------
// JSON storage
// -----------------------------------------------------------------------------
//
// Supported JSON format:
//
// {
//   "users": [
//     {
//       "username": "admin",
//       "password_hash": "pbkdf2-sha256$150000$...$...",
//       "enabled": true,
//       "roles": ["admin"]
//     }
//   ]
// }

type JSONStorage struct {
	path string

	mu    sync.RWMutex
	users map[string]User
}

type jsonUsersFile struct {
	Users []User `json:"users"`
}

func NewJSONStorage(path string) (*JSONStorage, error) {
	s := &JSONStorage{
		path:  path,
		users: make(map[string]User),
	}
	if err := s.Reload(); err != nil {
		return nil, err
	}
	return s, nil
}

func (s *JSONStorage) GetUser(username string) (User, bool, error) {
	s.mu.RLock()
	user, ok := s.users[username]
	s.mu.RUnlock()

	if !ok {
		return User{}, false, nil
	}

	return cloneUser(user), true, nil
}

func (s *JSONStorage) Reload() error {
	users, err := LoadUsersJSON(s.path)
	if err != nil {
		return err
	}

	next := make(map[string]User, len(users))
	for _, user := range users {
		next[user.Username] = cloneUser(user)
	}

	s.mu.Lock()
	s.users = next
	s.mu.Unlock()

	return nil
}

func LoadUsersJSON(path string) ([]User, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var wrapped jsonUsersFile
	if err := json.Unmarshal(b, &wrapped); err == nil && wrapped.Users != nil {
		return validateUsers(wrapped.Users)
	}

	var direct []User
	if err := json.Unmarshal(b, &direct); err != nil {
		return nil, err
	}

	return validateUsers(direct)
}

func SaveUsersJSON(path string, users []User) error {
	b, err := json.MarshalIndent(jsonUsersFile{Users: users}, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, b, 0600)
}

func validateUsers(users []User) ([]User, error) {
	for i := range users {
		if users[i].Username == "" {
			return nil, fmt.Errorf("basicauth: empty username at user index %d", i)
		}
		if users[i].PasswordHash == "" {
			return nil, fmt.Errorf("basicauth: empty password_hash for user %q", users[i].Username)
		}
	}
	return users, nil
}

// -----------------------------------------------------------------------------
// PBKDF2-SHA256 hasher
// -----------------------------------------------------------------------------

type PBKDF2Hasher struct {
	Iterations int
	SaltBytes  int
	KeyBytes   int
}

func DefaultHasher() *PBKDF2Hasher {
	return &PBKDF2Hasher{
		Iterations: 150000,
		SaltBytes:  16,
		KeyBytes:   32,
	}
}

func HashPassword(password string) (string, error) {
	return DefaultHasher().Hash(password)
}

func MustHashPassword(password string) string {
	hash, err := HashPassword(password)
	if err != nil {
		panic(err)
	}
	return hash
}

func (h *PBKDF2Hasher) Hash(password string) (string, error) {
	iterations := h.Iterations
	if iterations <= 0 {
		iterations = 150000
	}

	saltBytes := h.SaltBytes
	if saltBytes <= 0 {
		saltBytes = 16
	}

	keyBytes := h.KeyBytes
	if keyBytes <= 0 {
		keyBytes = 32
	}

	salt := make([]byte, saltBytes)
	if _, err := rand.Read(salt); err != nil {
		return "", err
	}

	key := pbkdf2Key([]byte(password), salt, iterations, keyBytes, sha256.New)

	return hashPrefix +
		"$" + strconv.Itoa(iterations) +
		"$" + base64.RawStdEncoding.EncodeToString(salt) +
		"$" + base64.RawStdEncoding.EncodeToString(key), nil
}

func (h *PBKDF2Hasher) Verify(password string, encodedHash string) bool {
	parts := strings.Split(encodedHash, "$")
	if len(parts) != 4 {
		return false
	}

	if subtle.ConstantTimeCompare([]byte(parts[0]), []byte(hashPrefix)) != 1 {
		return false
	}

	iterations, err := strconv.Atoi(parts[1])
	if err != nil || iterations <= 0 {
		return false
	}

	salt, err := base64.RawStdEncoding.DecodeString(parts[2])
	if err != nil || len(salt) == 0 {
		return false
	}

	expected, err := base64.RawStdEncoding.DecodeString(parts[3])
	if err != nil || len(expected) == 0 {
		return false
	}

	actual := pbkdf2Key([]byte(password), salt, iterations, len(expected), sha256.New)

	return subtle.ConstantTimeCompare(actual, expected) == 1
}

func pbkdf2Key(password, salt []byte, iter, keyLen int, h func() hash.Hash) []byte {
	prf := hmac.New(h, password)
	hashLen := prf.Size()
	numBlocks := (keyLen + hashLen - 1) / hashLen

	var buf [4]byte
	dk := make([]byte, 0, numBlocks*hashLen)
	u := make([]byte, hashLen)

	for block := 1; block <= numBlocks; block++ {
		prf.Reset()
		prf.Write(salt)
		binary.BigEndian.PutUint32(buf[:], uint32(block))
		prf.Write(buf[:])
		sum := prf.Sum(nil)

		t := make([]byte, hashLen)
		copy(t, sum)
		copy(u, sum)

		for i := 2; i <= iter; i++ {
			prf.Reset()
			prf.Write(u)
			u = prf.Sum(u[:0])

			for x := 0; x < hashLen; x++ {
				t[x] ^= u[x]
			}
		}

		dk = append(dk, t...)
	}

	return dk[:keyLen]
}

// -----------------------------------------------------------------------------
// Helpers
// -----------------------------------------------------------------------------

func splitList(s string) []string {
	if s == "" {
		return nil
	}

	fields := strings.FieldsFunc(s, func(r rune) bool {
		return r == '|' || r == ',' || r == ';'
	})

	out := make([]string, 0, len(fields))
	for _, f := range fields {
		f = strings.TrimSpace(f)
		if f != "" {
			out = append(out, f)
		}
	}

	return out
}

func cloneUser(user User) User {
	return User{
		Username:     user.Username,
		PasswordHash: user.PasswordHash,
		Enabled:      user.Enabled,
		Roles:        cloneStrings(user.Roles),
		Metadata:     cloneMap(user.Metadata),
	}
}

func cloneStrings(in []string) []string {
	if len(in) == 0 {
		return nil
	}
	out := make([]string, len(in))
	copy(out, in)
	return out
}

func cloneMap(in map[string]string) map[string]string {
	if len(in) == 0 {
		return nil
	}
	out := make(map[string]string, len(in))
	for k, v := range in {
		out[k] = v
	}
	return out
}
